name: poopy
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - gdal
  - libgdal-hdf5
  - libgdal-netcdf
  - geojson
  - matplotlib
  - numpy
  - pandas
  - pooch
  - python
  - pytest
  - requests
  - shapely
